#!/bin/bash

########################################################################
# make_cmd_reference.sh
#
# This script generates a documentation file with the command reference
# for each of the tools in the SNP Pipeline.  This is part of the
# RST/Sphinx documentation for the SNP Pipeline.
#
# This script should be manually executed before each release to 
# capture the changes since the last release.
#
# Input : None
# Output: cmd_ref.rst
#
########################################################################

echo > x.txt
echo '.. DO NOT EDIT.' >> x.txt
echo '.. This file is machine generated by the make_cmd_reference.sh script.' >> x.txt
echo >> x.txt
echo '.. _cmd-ref-label:' >> x.txt
echo >> x.txt
echo ================= >> x.txt
echo Command Reference >> x.txt
echo ================= >> x.txt
echo >> x.txt

echo copy_snppipeline_data.py >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
copy_snppipeline_data.py  -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo '.. _cmd-ref-run-snp-pipeline:' >> x.txt
echo >> x.txt
echo run_snp_pipeline.sh      >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
run_snp_pipeline.sh       -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo prepReference.sh         >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
prepReference.sh          -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo alignSampleToReference.sh >> x.txt
echo ------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
alignSampleToReference.sh -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo prepSamples.sh           >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
prepSamples.sh            -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo create_snp_list.py          >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
create_snp_list.py        -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo create_snp_pileup.py        >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
create_snp_pileup.py      -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo '.. _cmd-ref-call-consensus:' >> x.txt
echo >> x.txt
echo call_consensus.py        >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
call_consensus.py      -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo >> x.txt
echo mergeVcf.sh >> x.txt
echo --------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
mergeVcf.sh -h | sed 's/^/  /' >> x.txt

echo create_snp_matrix.py     >> x.txt
echo ------------------------ >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
create_snp_matrix.py      -h | sed 's/^/  /' >> x.txt
echo >> x.txt

echo >> x.txt
echo calculate_snp_distances.py >> x.txt
echo --------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
calculate_snp_distances.py -h | sed 's/^/  /' >> x.txt

echo create_snp_reference_seq.py >> x.txt
echo --------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
create_snp_reference_seq.py -h | sed 's/^/  /' >> x.txt

echo >> x.txt
echo collectSampleMetrics.sh >> x.txt
echo --------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
collectSampleMetrics.sh -h | sed 's/^/  /' >> x.txt

echo >> x.txt
echo combineSampleMetrics.sh >> x.txt
echo --------------------------- >> x.txt
echo >> x.txt; echo :: >> x.txt; echo >> x.txt
combineSampleMetrics.sh -h | sed 's/^/  /' >> x.txt

cat x.txt | 
sed 's~/home/steven.davis/.virtualenvs/snp-pipeline-2.7/bin/~~' | \
sed 's~/home/steven.davis/.virtualenvs/snp-pipeline-3.5/bin/~~' | \
grep -v "# Command           :" | \
grep -v "# Working Directory :" | \
grep -v "# Hostname          :" | \
grep -v "# RAM               :" > cmd_ref.rst

rm x.txt
